# This file was generated by GoReleaser. DO NOT EDIT.
class CruxCheck < Formula
  desc "CLI for checking CrUX data."
  homepage "https://github.com/whamondg/homebrew-crux-check"
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/whamondg/crux-check/releases/download/v0.3.0/crux-check_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "27d3c02fd85ad8514ef08dda7e8ff51548cffdeca487ff862af36324ce237bb7"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/whamondg/crux-check/releases/download/v0.3.0/crux-check_0.3.0_Linux_x86_64.tar.gz"
    sha256 "16f36eaa4424c7e4eef9230f12faa80b6cbdddfcc99cfa61518b3122ca429d2d"
  end

  def install
    bin.install "crux-check"
  end

  test do
    system "#{bin}/crux-check -h"
  end
end
