# This file was generated by GoReleaser. DO NOT EDIT.
class CruxCheck < Formula
  desc "CLI for checking CrUX data."
  homepage "https://github.com/whamondg/homebrew-crux-check"
  version "0.0.3-alpha"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/whamondg/crux-check/releases/download/v0.0.3-alpha/crux-check_0.0.3-alpha_Darwin_x86_64.tar.gz"
    sha256 "ac0a1f9b03ab0ef25378aa18f45d7ad62391ed55e1ded29cf4e13337643a2366"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/whamondg/crux-check/releases/download/v0.0.3-alpha/crux-check_0.0.3-alpha_Linux_x86_64.tar.gz"
    sha256 "11667bfd9cee50112f51def70f7572bde5af27f95b38cf0e13e4fffe545d5a93"
  end

  def install
    bin.install "crux-check"
  end

  test do
    system "#{bin}/crux-check -h"
  end
end
